version: "3.1"
services:
  apache:
    image: httpd:latest
    build: .
    ports: 
      - "8003:80"
    volumes:
      - ./www:/var/www/html/
    links: 
      - db
    networks: 
      - default
  
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: football
      MYSQL_USER: jack
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    networks: 
      - default
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - "8004:80"
    environment:
      MYSQL_USER: jack
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
volumes:
    persistent:

